config_path: src/object_detection/config/experiment_config/config_yolov5lu_dataset_3_exp_dataset_size_7.yaml
data:
  bboxes_path: ./dataset/3/Handcrafted_dataset/bboxes.csv
  dataset: '3'
  dataset_size: '100'
  path_to_dataset: ./dataset
  shuffle_train: true
  split: experiments/dataset_split/Dataset_3_DatasetSize_100_Train_50_Val_20_Split.yaml
  test_split: 0
  train_split: '0.5'
  val_split: '0.2'
  yolo_dataset: ./dataset/3/yolo_datasets/DatasetSize_100_Train_50_Val_20
dataset:
  binarization_method: HSV
  dist_tolerance_inter_rows: 0.25
  dist_tolerance_on_row: 0.05
  image_size: 224
  inter_row_distance: 0.75
  load_orthomosaic: false
  max_dist_on_row: 0.18
  max_leaf_area: 0.01
  min_dist_on_row: 0.12
  min_leaf_area: 0.001
  resolution: 0.005
experiment:
  id: yolov5lu_dataset_3_exp_dataset_size_7
  note: dataset_size
  seed: 123
predict:
  prediction_path: experiments/predictions/dataset_size/yolov5lu_dataset_3_exp_dataset_size_7.shp
train:
  batch_size: 16
  max_epoch: 200
  model: yolov5lu
  model_checkpoint: experiments/models/dataset_size/yolov5lu_dataset_3_exp_dataset_size_7/weights/best.pt
  n_workers: 8
  num_classes: 2
  optimizer: auto
  patience: 15
  seed: 123
  use_pretrained: true
