[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "torch==1.13.1",
    "cloudpickle",
    "diffdist==0.1",
    "fast_pytorch_kmeans",
    "fire",
    "matplotlib",
    "numpy==1.22.4",
    "pycocotools==2.0.6",
    "scikit_learn==1.3.0",
    "seaborn==0.12.2",
    "Shapely==2.0.1",
    "timm==0.6.13",
    "torchvision==0.14.1",
    "tqdm",
    "xformers==0.0.16",
    "ftfy==6.1.1",
    "fvcore",
    "info-nce-pytorch"
]
build-backend = "setuptools.build_meta"